/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guialab16_01;

/**
 *
 * @author PROFESOR
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbAuto1 = new javax.swing.JComboBox<>();
        cmbAuto2 = new javax.swing.JComboBox<>();
        chkAlerones1 = new javax.swing.JCheckBox();
        chkNeumaticos1 = new javax.swing.JCheckBox();
        chkCombustible1 = new javax.swing.JCheckBox();
        chkSuspension1 = new javax.swing.JCheckBox();
        chkTimon1 = new javax.swing.JCheckBox();
        btnIniciarCarrera = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtVelocidadAuto1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVelocidadAuto2 = new javax.swing.JTextField();
        chkTimon2 = new javax.swing.JCheckBox();
        chkAlerones2 = new javax.swing.JCheckBox();
        chkNeumaticos2 = new javax.swing.JCheckBox();
        chkCombustible2 = new javax.swing.JCheckBox();
        chkSuspension2 = new javax.swing.JCheckBox();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Auto 1");

        jLabel2.setText("Auto 2");

        cmbAuto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un auto...", "Jaguar", "Ferrari", "Lamborghini" }));
        cmbAuto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAuto1ActionPerformed(evt);
            }
        });

        chkAlerones1.setText("Alerones aerodinámicos");

        chkNeumaticos1.setText("Neumáticos Dunlop");

        chkCombustible1.setText("Combustible Premium");

        chkSuspension1.setText("Suspensión diferenciada");

        chkTimon1.setText("Timón volante Racing Momo");

        btnIniciarCarrera.setText("Iniciar carrera...");
        btnIniciarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarCarreraActionPerformed(evt);
            }
        });

        jLabel3.setText("Velocidad Auto 1");

        jLabel4.setText("Velocidad Auto 2");

        chkTimon2.setText("Timón volante Racing Momo");

        chkAlerones2.setText("Alerones aerodinámicos");

        chkNeumaticos2.setText("Neumáticos Dunlop");

        chkCombustible2.setText("Combustible Premium");

        chkSuspension2.setText("Suspensión diferenciada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAlerones1)
                    .addComponent(chkTimon1)
                    .addComponent(chkSuspension1)
                    .addComponent(chkCombustible1)
                    .addComponent(chkNeumaticos1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAlerones2)
                    .addComponent(chkTimon2)
                    .addComponent(chkSuspension2)
                    .addComponent(chkCombustible2)
                    .addComponent(chkNeumaticos2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(btnIniciarCarrera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(cmbAuto1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAuto2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(txtVelocidadAuto1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtVelocidadAuto2)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cmbAuto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAuto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkAlerones1)
                        .addGap(18, 18, 18)
                        .addComponent(chkNeumaticos1)
                        .addGap(18, 18, 18)
                        .addComponent(chkCombustible1)
                        .addGap(18, 18, 18)
                        .addComponent(chkSuspension1)
                        .addGap(18, 18, 18)
                        .addComponent(chkTimon1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkAlerones2)
                        .addGap(18, 18, 18)
                        .addComponent(chkNeumaticos2)
                        .addGap(18, 18, 18)
                        .addComponent(chkCombustible2)
                        .addGap(18, 18, 18)
                        .addComponent(chkSuspension2)
                        .addGap(18, 18, 18)
                        .addComponent(chkTimon2)))
                .addGap(18, 18, 18)
                .addComponent(btnIniciarCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVelocidadAuto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtVelocidadAuto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAuto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAuto1ActionPerformed
        // TODO add your handling code here:
        //System.out.println(this.cmbAuto1.getSelectedIndex());
        
        cmbAuto2.removeAllItems();
        cmbAuto2.addItem(cmbAuto1.getItemAt(0));
        cmbAuto2.addItem(cmbAuto1.getItemAt(1));
        cmbAuto2.addItem(cmbAuto1.getItemAt(2));
        cmbAuto2.addItem(cmbAuto1.getItemAt(3));
        
        cmbAuto2.removeItemAt(cmbAuto1.getSelectedIndex());
    }//GEN-LAST:event_cmbAuto1ActionPerformed

    private void btnIniciarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarCarreraActionPerformed
        // TODO add your handling code here:
        AutoFactory autoFactory = new AutoFactory();
        Auto auto1 = autoFactory.seleccionarAuto(cmbAuto1.getSelectedIndex());
        
        int codigoAuto2;
        if(cmbAuto2.getSelectedItem().equals("Jaguar")) codigoAuto2 = 1;
        else if(cmbAuto2.getSelectedItem().equals("Ferrari")) codigoAuto2 = 2;
        else codigoAuto2 = 3;
        
        Auto auto2 = autoFactory.seleccionarAuto(codigoAuto2);
        
        //Los objetos auto1 y auto2 son los que se van a decorar de acuerdo
        //a los chkboxes que se hayan elegido
        
        if(chkAlerones1.isSelected()){
            auto1 = new Alerones(auto1);
        }
        
        if(chkNeumaticos1.isSelected()){
            auto1 = new Neumaticos(auto1);
        }
        
        if(chkCombustible1.isSelected()){
            auto1 = new Combustible(auto1);
        }
        
        if(chkSuspension1.isSelected()){
            auto1 = new Suspension(auto1);
        }
        
        if(chkTimon1.isSelected()){
            auto1 = new Timon(auto1);
        }
        /******************/
        
        if(chkAlerones2.isSelected()){
            auto2 = new Alerones(auto2);
        }
        
        if(chkNeumaticos2.isSelected()){
            auto2 = new Neumaticos(auto2);
        }
        
        if(chkCombustible2.isSelected()){
            auto2 = new Combustible(auto2);
        }
        
        if(chkSuspension2.isSelected()){
            auto2 = new Suspension(auto2);
        }
        
        if(chkTimon2.isSelected()){
            auto2 = new Timon(auto2);
        }
        
        txtVelocidadAuto1.setText(Integer.toString(auto1.getMaxVelocidad()));
        txtVelocidadAuto2.setText(Integer.toString(auto2.getMaxVelocidad()));
        
        Hilo a1, a2;
        
        a1 = new Hilo("Auto 1",1000-auto1.getMaxVelocidad());
        a2 = new Hilo("Auto 2",1000-auto2.getMaxVelocidad());
        
        a1.start();
        a2.start();
    }//GEN-LAST:event_btnIniciarCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarCarrera;
    private javax.swing.JCheckBox chkAlerones1;
    private javax.swing.JCheckBox chkAlerones2;
    private javax.swing.JCheckBox chkCombustible1;
    private javax.swing.JCheckBox chkCombustible2;
    private javax.swing.JCheckBox chkNeumaticos1;
    private javax.swing.JCheckBox chkNeumaticos2;
    private javax.swing.JCheckBox chkSuspension1;
    private javax.swing.JCheckBox chkSuspension2;
    private javax.swing.JCheckBox chkTimon1;
    private javax.swing.JCheckBox chkTimon2;
    private javax.swing.JComboBox<String> cmbAuto1;
    private javax.swing.JComboBox<String> cmbAuto2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtVelocidadAuto1;
    private javax.swing.JTextField txtVelocidadAuto2;
    // End of variables declaration//GEN-END:variables
}
